EMS/EMS/Controllers/DepartmetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.Models;

namespace EMS.Controllers
{
    public class DepartmetController : Controller
    {
        private EMSEntities db = new EMSEntities();

        public ActionResult Index()
        {
            if (Session["name"].ToString() == "admin")
            {
                return View(db.Departments.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        public ActionResult Create()
        {
            if (Session["name"].ToString() == "admin")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,DepartmentName")] Department department)
        {
            if(ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }
        public ActionResult Edit(int? id)
        {
            if (Session["name"].ToString() == "admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Department department = db.Departments.Find(id);
                if (department == null)
                {
                    return HttpNotFound();
                }
                return View(department);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentId,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }
        [HttpPost]
        public JsonResult CheckDepartment(string department)
        {
            bool value = db.Departments.ToList().Exists(x => x.DepartmentName.ToLower().Equals(department.ToLower()));

            return Json(value);
        }
    }
}

EMS/EMS/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.Models;

namespace EMS.Controllers
{
    public class EmployeeController : Controller
    {
        private EMSEntities db = new EMSEntities();

        public ActionResult Index()
        {
            if (Session["name"].ToString() == "admin")
            {
                return View(db.EmployeeInfoes.ToList());
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        public ActionResult Create()
        {
            if (Session["name"].ToString() == "admin")
            {
                ViewBag.DesignationId = new SelectList(db.Designations, "DesignationId", "DesignationName");
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeId,EmployeeName,EmployeeGender,EmployeeEmail,EmployeePassword,EmployeePhone,DesignationId")] EmployeeInfo employee)
        {
            if (ModelState.IsValid)
            {
                db.EmployeeInfoes.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DesignationId = new SelectList(db.Designations, "DesignationId", "DesignationName", employee.DesignationId);
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (Session["name"].ToString() == "admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EmployeeInfo employee = db.EmployeeInfoes.Find(id);
                if (employee == null)
                {
                    return HttpNotFound();
                }
                ViewBag.DesignationId = new SelectList(db.Designations, "DesignationId", "DesignationName", employee.DesignationId);
                return View(employee);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeId,EmployeeName,EmployeeGender,EmployeeEmail,EmployeePassword,EmployeePhone,DesignationId")] EmployeeInfo employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DesignationId = new SelectList(db.Designations, "DesignationId", "DesignationName", employee.DesignationId);
            return View();
        }

        public ActionResult EmployeeProfile(int? id)
        {
            if (Session["id"] != null && Session["name"].ToString() == "employee")
            {
                id = Convert.ToInt16(Session["id"]);
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                EmployeeInfo employeeInfo = db.EmployeeInfoes.Find(id);
                if (employeeInfo == null)
                {
                    return HttpNotFound();
                }
                return View(employeeInfo);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }

        public ActionResult SalaryById(int? id)
        {
            if (Session["id"] != null && Session["name"].ToString() == "employee")
            {
                id = Convert.ToInt16(Session["id"]);

                var employeeSalary = db.Salaries.Where(x => x.EmployeeId == id).OrderByDescending(x => x.SalaryId).ToList();

                return View(employeeSalary);
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }
    }
}

EMS/EMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Employee Management System</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ionicons.min.css" rel="stylesheet" />
    <link href="~/Content/AdminLTE.css" rel="stylesheet" />
    <link href="~/Content/_all-skins.css" rel="stylesheet" />

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="~/Content/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
</head>
<body class="hold-transition skin-blue sidebar-mini">

    <header class="main-header">
        <div href="" class="logo">
            <span>
                <img src="~/Image/Logo.png" height="50" width="50" class="pull-left" />
            </span>
          
            <span class="logo-lg"><b>Qbytesoft</b></span>
        </div>
        <nav class="navbar navbar-static-top">

            @*<a href="#" class="sidebar-toggle" data-toggle="push-menu">
                    <span class="sr-only"></span>
                </a>*@
            <div class="pull-right">
                @if (Session["id"] != null) //Home Panel
                {
                    using (Html.BeginForm("Logout", "Home", FormMethod.Post, new { id = "logout" }))
                    {
                        <a href="javascript:document.getElementById('logout').submit()" class="btn btn-default btn-flat">Sign out</a>
                    }
                }
                else
                {
                    @Html.ActionLink("Attendence","Create","Attendence", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Login", "Login", "Home", new { area = "" }, new { @class = "navbar-brand" })

                }
            </div>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    @if (Session["id"] != null && Session["name"].ToString() == "admin")
                    {
                        @Html.ActionLink("Employee List", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Department", "Index", "Departmet", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Designation", "Index", "Designation", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Salary", "Index", "Salary", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Attendence List", "Index", "Attendence", new { area = "" }, new { @class = "navbar-brand" })
                    }
                    @if(Session["id"] != null && Session["name"].ToString() == "employee")
                    {

                        @Html.ActionLink("Total Working Hour", "AttendenceById", "Attendence", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Salary", "SalaryById", "Employee", new { area = "" }, new { @class = "navbar-brand" })

                    }
                    @*<li>
            <div>
                @using (Html.BeginForm("Logout", "Login", FormMethod.Post, new { id = "logout" }))
                {
                    <a href="javascript:document.getElementById('logout').submit()" class="btn btn-default btn-flat">Sign out</a>
                }

            </div>
        </li>*@
                    @*<li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="hidden-xs">##### <i class=" fa fa-angle-down"></i></span>
            </a>
            <ul class="dropdown-menu">
                <li>


                        <a href="#">Change Password</a>



                        <a href="#">Sign out</a>



                </li>
            </ul>
        </li>*@

                    @*<li class="dropdown user user-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="hidden-xs">##### <i class=" fa fa-angle-down"></i></span>
            </a>
            <ul class="dropdown-menu">


                @*<li class="user-footer">
                        <div class="pull-left">
                            @if (Session["id"].ToString() != "admin")
                            {
                                <a href="/UserProfile/ChangePassword" class="btn btn-default btn-flat">Change Password</a>
                            }
                        </div>
                        <div class="pull-right">
                            @using (Html.BeginForm("Logout", "Login", FormMethod.Post, new { id = "logout" }))
                            {
                                <a href="javascript:document.getElementById('logout').submit()" class="btn btn-default btn-flat">Sign out</a>
                            }

                        </div>
                    </li>
            </ul>
        </li>*@



                </ul>
            </div>

        </nav>
    </header>
    @*<aside class="main-sidebar">
            <section class="sidebar">
                <ul class="sidebar-menu" data-widget="tree">
                    @if (Session["id"] != null && Session["id"].ToString() != "admin")
                    {
                        <li><a href="~/UserProfile/Details"><span><i class="glyphicon glyphicon-book"></i> Profile Page</span></a></li>
                        <li><a href="~/UserProfile/ChangePassword">Change Password</a></li>
                    }
                    @if (Session["id"] != null && Session["id"].ToString() == "admin")
                    {
                        <li><a href="~/UserProfile/Index"><i class="glyphicon glyphicon-book"></i> User List</a></li>

                    }
                </ul>
            </section>
        </aside>*@
    <div class="body-content" style="margin-top:-20px!important;width:100%!important">
        @RenderBody()
        <hr />

    </div>
    @*<div class="control-sidebar-bg"></div>*@

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script type="text/javascript" language="javascript" class="init">
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/adminlte.min.js"></script>
    <script src="~/Scripts/dashboard2.js"></script>
    <script src="~/Scripts/demo.js"></script>
</body>
</html>